---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  vars:
    freeipa_client_test_mode: true

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-apps_freeipa_client
