---
- name: "DEBIAN11: Install FreeIPA required packages"
  ansible.builtin.package:
    name: "{{ freeipa_client_pkgs_required }}"
    state: present
    update_cache: "{{ omit if (ansible_pkg_mgr == 'dnf') else 'yes' }}"
  delay: 10
  register: result
  retries: 3
  until: result is succeeded

- name: "DEBIAN11:  Ensure xz-utils is present"
  ansible.builtin.package:
    name: xz-utils
    state: present

- name: "DEBIAN11: Copy freeipa deb files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp
    mode: '0644'
  with_items:
    - "{{ freeipa_client_deb_pkgs }}"

- name: "DEBIAN11: Install deb packages from the internet"
  ansible.builtin.apt:
    deb: "/tmp/{{ item }}"
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  with_items:
    - "{{ freeipa_client_deb_pkgs }}"
